# Generated by Django 4.1.7 on 2023-04-05 23:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=5000)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('autor', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('contenido', models.CharField(max_length=5000)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('autor', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaComentario',
            fields=[
                ('comentario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='AppBlog.comentario')),
                ('contenido', models.CharField(max_length=5000)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('autor', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.posteo'),
        ),
    ]
